### ISSUE TITLE
Video frames added from other video

### ISSUE THREAD

**Issue by zecretaccount** [mike9251/simswap-inference-pytorch#10]
Hey 
When I use the faceswap video (single image) config and take a video that is, lets say 300 frames. The right after, if I run the config with a video of 200 frames, the 100 extra frames from before will be added to the video.

 I simply fix it by deleting the folder with all the frames from last time, so this could probably be added to the code as well :)
 I know simswap just deletes them every time it starts a run.

**Comment by mike9251** [comment]
Right now it is an expected behavior. I'll add this functionality later.

**Comment by zecretaccount** [comment]
@mike9251  cool, I'll just use a command for it for batching as it is now :)
