### ISSUE TITLE
Error in latest source

### ISSUE THREAD

**Issue by zecretaccount** [mike9251/simswap-inference-pytorch#11]
![image](https://user-images.githubusercontent.com/118489915/206895831-b65c0206-4c80-4144-9b79-616dc5e219de.png)
I'm receving this error after updating the repo. Very odd, it actually ran a few times with some videos before doing this.

**Comment by mike9251** [comment]
Can you share the video where you see this error?

**Comment by Akyariss** [comment]
I'm getting the same error

**Comment by zecretaccount** [comment]
> Can you share the video where you see this error?

Hi Mike
Yeah I uploaded here: https://easyupload.io/m/ceevbe
On some videos it works, but most videos it says this error. It does swap to the "img" folder alright, but collecting them to a video? nope, not always.

**Comment by mike9251** [comment]
Fixed. Also now you can set a parameter `clean_work_dir` to automatically remove image folder after video is created.

**Comment by zecretaccount** [comment]
Awesome @mike9251  ! It works and the clean dir parameter is nice :D
