### ISSUE TITLE
Square around swapped face 

### ISSUE THREAD

**Issue by Akyariss** [mike9251/simswap-inference-pytorch#12]
Hi, after the GFPGAN update i'm getting squares around the swapped faces with and without using GFPGAN
Usually when the subject is not in front of the camera

The allignment type, erode mask value, smooth mask value and detector threshold are the same from the last version

Testing the same input with the older version does not make the squares appear

**Comment by mike9251** [comment]
Hi, can you share the data where you see this issue? Having data to reproduce the problem will help me fix it quicker.

**Comment by mike9251** [comment]
does it look like this?

https://user-images.githubusercontent.com/25375369/206930690-1b642a03-f12d-45c1-b059-eb414ef7da78.mp4

Fixed

https://user-images.githubusercontent.com/25375369/206930743-b9f5dd0e-c6cd-4ff2-9d6f-b3b87babba0b.mp4

If you see this problem again, you might wanna tune the `sigma_scale_value` parameter.

**Comment by zecretaccount** [comment]
works for me

**Comment by Akyariss** [comment]
Thank you! works for me too
