### ISSUE TITLE
GFPGAN Model and multispecific

### ISSUE THREAD

**Issue by DrBlou** [mike9251/simswap-inference-pytorch#23]
Hi :)

I have 2 questions please : 

1: I wanted to know if its possible to change the gfpgan model for post processing ? Like using the 1.2 or 1.3 version ?

2: Is it possible to do a multispecific swap like in the original simswap ?

Thanks again for your work and time

Have a nice day

**Comment by mike9251** [comment]
Hi @DrBlou , 1. If the model architecture is the same then it should work. But in general you can't just swap weights from a different model without changing the model definition.
2. No, right now this repo doesn't support it.

**Comment by DrBlou** [comment]
Thank you
