### ISSUE TITLE
Only cpu!

### ISSUE THREAD

**Issue by phoelion** [mike9251/simswap-inference-pytorch#29]
does it able to run **only** on the **CPU**??????
I have no GPUs,
after installing Pytorch on the CPU it simply asks for **GPU** or **CUDA**.
@mike9251

**Comment by mike9251** [comment]
Yes, it supports running on CPU. You need to specify it in the config file: **device: "cpu"**

**Comment by mike9251** [comment]
Although I didn't check it with CPU compiled pytorch, I guess it should work (only tried it with cuda pytorch)

**Comment by phoelion** [comment]
Thanks, it worked fine.
